use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

pub const COLLECTION_NAME: &str = "catalog_delegation_grants";

/// Online authority record for a delegated token carrying `mcp:catalog:read`.
///
/// The signed JWT remains the bearer credential. This short-lived record is
/// the revocation and live-policy anchor used to reject stale or altered
/// catalog authority before a request reaches a catalog handler.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogDelegationGrant {
    /// The delegated JWT's `jti`; UUID v4 generated by the JWT issuer.
    #[serde(rename = "_id")]
    pub id: String,
    pub user_id: String,
    pub actor_client_id: String,
    pub receiving_client_id: String,
    pub scope: String,
    pub resources: Vec<String>,
    pub allow_all_services: bool,
    pub allowed_service_ids: Vec<String>,
    pub allow_all_nodes: bool,
    pub allowed_node_ids: Vec<String>,
    pub revoked: bool,
    #[serde(with = "bson::serde_helpers::chrono_datetime_as_bson_datetime")]
    pub expires_at: DateTime<Utc>,
    #[serde(with = "bson::serde_helpers::chrono_datetime_as_bson_datetime")]
    pub created_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bson_roundtrip_preserves_explicit_empty_authority() {
        let now = Utc::now();
        let grant = CatalogDelegationGrant {
            id: uuid::Uuid::new_v4().to_string(),
            user_id: uuid::Uuid::new_v4().to_string(),
            actor_client_id: "nyxid-assistant".to_string(),
            receiving_client_id: "aevatar".to_string(),
            scope: "mcp:catalog:read".to_string(),
            resources: Vec::new(),
            allow_all_services: false,
            allowed_service_ids: Vec::new(),
            allow_all_nodes: false,
            allowed_node_ids: Vec::new(),
            revoked: false,
            expires_at: now,
            created_at: now,
        };

        let document = bson::to_document(&grant).expect("serialize catalog delegation grant");
        let restored: CatalogDelegationGrant =
            bson::from_document(document).expect("deserialize catalog delegation grant");
        assert_eq!(restored, grant);
    }
}
