import { useRef, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { api } from "@/lib/api-client";
import { actionControlIdentitySchema } from "@/schemas/assistant-actions";
import { assertSecretFreeReadBack, errorMessage } from "./assistant-action-dialog-utils";

const paramsSchema = z.object({ grantId: actionControlIdentitySchema }).strict();
const responseSchema = z.object({ resource: z.object({ grantId: actionControlIdentitySchema }).strict(), replayed: z.boolean() }).strict();
const evidenceSchema = z.object({ id: actionControlIdentitySchema, revoked: z.boolean() }).passthrough();

export function AssistantApprovalRevokeGrantDialog({ open, onOpenChange, actionRequestId, params, onComplete }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly actionRequestId: string; readonly params: { grantId: string }; readonly onComplete: (grantId: string) => void; }) {
  const submittingRef = useRef(false); const [submitting, setSubmitting] = useState(false); const [confirmed, setConfirmed] = useState(false); const [resultGrantId, setResultGrantId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  function close() { submittingRef.current = false; setSubmitting(false); setConfirmed(false); setResultGrantId(null); setError(null); onOpenChange(false); }
  async function submit() { if (submittingRef.current || resultGrantId) return; submittingRef.current = true; setSubmitting(true); setError(null); try { const expected = paramsSchema.parse(params); const beforeValue = await api.get<unknown>(`/approvals/grants/${encodeURIComponent(expected.grantId)}/authorization`); assertSecretFreeReadBack(beforeValue); const before = evidenceSchema.parse(beforeValue); if (before.revoked) throw new Error("This grant is already revoked."); const response = responseSchema.parse(await api.post<unknown>("/assistant/actions/org/approval/revoke-grant", { actionRequestId, grantId: expected.grantId })); const afterValue = await api.get<unknown>(`/approvals/grants/${encodeURIComponent(expected.grantId)}/authorization`); assertSecretFreeReadBack(afterValue); const after = evidenceSchema.parse(afterValue); if (after.id !== response.resource.grantId || !after.revoked) throw new Error("NyxID could not verify grant revocation."); setResultGrantId(response.resource.grantId); } catch (caught) { setError(errorMessage(caught, "NyxID could not revoke this grant.")); } finally { submittingRef.current = false; setSubmitting(false); } }
  return <Dialog open={open} onOpenChange={(next) => !next && close()}><DialogContent><DialogHeader><DialogTitle>{resultGrantId ? "Grant revoked" : "Revoke approval grant"}</DialogTitle><DialogDescription>{resultGrantId ? "The grant projection confirms it is revoked." : "This destructive action is confirmed every time and cannot be remembered."}</DialogDescription></DialogHeader>{!resultGrantId ? <div className="space-y-3 border-y border-border py-4"><p className="font-mono text-[12px] text-muted-foreground">{params.grantId}</p><label className="flex items-start gap-2 text-[12px]"><Checkbox checked={confirmed} onCheckedChange={(value) => setConfirmed(value === true)} /><span>I understand that callers will need a fresh approval.</span></label></div> : null}{error ? <p role="alert" className="text-[11px] text-destructive">{error}</p> : null}<DialogFooter>{resultGrantId ? <Button type="button" variant="primary" onClick={() => { onComplete(resultGrantId); close(); }}>Done</Button> : <><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="button" variant="destructive" isLoading={submitting} disabled={submitting || !confirmed} onClick={() => void submit()}>Revoke grant</Button></>}</DialogFooter></DialogContent></Dialog>;
}
