import { useRef, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { api } from "@/lib/api-client";
import { actionControlIdentitySchema } from "@/schemas/assistant-actions";
import { assertSecretFreeReadBack, errorMessage, isNewerTimestamp } from "./assistant-action-dialog-utils";

const paramsSchema = z.object({ serviceId: actionControlIdentitySchema }).strict();
const responseSchema = z.object({ resource: z.object({ serviceId: actionControlIdentitySchema }).strict(), replayed: z.boolean() }).strict();
const evidenceSchema = z.object({ service_id: actionControlIdentitySchema, approval_required: z.boolean(), updated_at: z.string().datetime({ offset: true }) }).passthrough();

export function AssistantApprovalToggleDialog({ open, onOpenChange, actionRequestId, params, mode, onComplete }: { readonly open: boolean; readonly onOpenChange: (open: boolean) => void; readonly actionRequestId: string; readonly params: { serviceId: string }; readonly mode: "enable" | "disable"; readonly onComplete: (serviceId: string) => void; }) {
  const submittingRef = useRef(false); const [submitting, setSubmitting] = useState(false); const [confirmed, setConfirmed] = useState(false); const [resultServiceId, setResultServiceId] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  function close() { submittingRef.current = false; setSubmitting(false); setConfirmed(false); setResultServiceId(null); setError(null); onOpenChange(false); }
  async function submit() { if (submittingRef.current || resultServiceId) return; submittingRef.current = true; setSubmitting(true); setError(null); try { const expected = paramsSchema.parse(params); const beforeValue = await api.get<unknown>(`/approvals/service-configs/${encodeURIComponent(expected.serviceId)}/authorization`); assertSecretFreeReadBack(beforeValue); const before = evidenceSchema.parse(beforeValue); const response = responseSchema.parse(await api.post<unknown>(`/assistant/actions/org/approval/${mode}`, { actionRequestId, serviceId: expected.serviceId })); const afterValue = await api.get<unknown>(`/approvals/service-configs/${encodeURIComponent(expected.serviceId)}/authorization`); assertSecretFreeReadBack(afterValue); const after = evidenceSchema.parse(afterValue); const expectedRequired = mode === "enable"; if (after.service_id !== response.resource.serviceId || after.approval_required !== expectedRequired || !isNewerTimestamp(before.updated_at, after.updated_at)) throw new Error("NyxID could not verify the approval toggle."); setResultServiceId(response.resource.serviceId); } catch (caught) { setError(errorMessage(caught, "NyxID could not change this approval policy.")); } finally { submittingRef.current = false; setSubmitting(false); } }
  const destructive = mode === "disable";
  return <Dialog open={open} onOpenChange={(next) => !next && close()}><DialogContent><DialogHeader><DialogTitle>{resultServiceId ? `Approvals ${mode}d` : `${mode === "enable" ? "Enable" : "Disable"} approvals`}</DialogTitle><DialogDescription>{resultServiceId ? "The approval projection confirms the change." : destructive ? "Disabling approvals weakens this service's safety control. Confirm every time." : "Require an approval before this service executes."}</DialogDescription></DialogHeader>{!resultServiceId ? <div className="space-y-3 border-y border-border py-4"><p className="font-mono text-[12px] text-muted-foreground">{params.serviceId}</p>{destructive ? <label className="flex items-start gap-2 text-[12px]"><Checkbox checked={confirmed} onCheckedChange={(value) => setConfirmed(value === true)} /><span>I understand that disabling this control weakens the service policy.</span></label> : null}</div> : null}{error ? <p role="alert" className="text-[11px] text-destructive">{error}</p> : null}<DialogFooter>{resultServiceId ? <Button type="button" variant="primary" onClick={() => { onComplete(resultServiceId); close(); }}>Done</Button> : <><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="button" variant={destructive ? "destructive" : "primary"} isLoading={submitting} disabled={submitting || (destructive && !confirmed)} onClick={() => void submit()}>{destructive ? "Disable approvals" : "Enable approvals"}</Button></>}</DialogFooter></DialogContent></Dialog>;
}
