import { describe, expect, it } from "vitest";
import contract from "@/schemas/__fixtures__/platform-ops-contract.json";
import {
  platformOperationDiscoveryListSchema,
  platformOperationListSchema,
} from "./platform-ops";

/**
 * The fixture is generated by backend/src/platform_ops_contract_tests.rs from
 * the same projection functions the handlers use, and a Rust test fails if it
 * drifts from them. Parsing it here with the real schemas is what ties the two
 * languages together.
 *
 * The hand-written fixtures in platform-ops.test.ts cannot do this job: they
 * kept passing while the schemas required `metric: "requests"` and the backend
 * had already moved `speak` to `characters`, so the admin page failed to parse
 * its own default state with a green test suite.
 */
describe("platform operations backend contract", () => {
  it("parses the admin list response the backend actually serializes", () => {
    const parsed = platformOperationListSchema.parse(contract.admin);

    expect(parsed.operations.map((operation) => operation.op)).toEqual([
      "speak",
      "call_and_say",
      "flight_search",
    ]);
  });

  it("parses the discovery response the backend actually serializes", () => {
    const parsed = platformOperationDiscoveryListSchema.parse(
      contract.discovery,
    );

    expect(parsed.operations).toHaveLength(3);
  });

  it("accepts every metric the backend can bill, not just requests", () => {
    const parsed = platformOperationListSchema.parse(contract.admin);

    expect(parsed.operations.map((operation) => operation.pricing.metric))
      .toEqual(["characters", "seconds", "requests"]);
  });

  it("carries a server-rendered price for each priced shape", () => {
    const parsed = platformOperationListSchema.parse(contract.admin);

    expect(parsed.operations.map((operation) => operation.pricing.display))
      .toEqual([
        "0.002 credits per character",
        "1.5 credits per call + 0.05 per second",
        "Free",
      ]);
  });

  it("exposes Lago sync state so the admin table can report it", () => {
    const parsed = platformOperationListSchema.parse(contract.admin);
    const failed = parsed.operations[1];

    expect(failed?.pricing.sync_status).toBe("failed");
    expect(failed?.pricing.sync_error).toBe(
      "lago rejected the charge payload",
    );
  });
});
