/** MCP endpoint of the hosted NyxID instance the published plugins point at. */
export const HOSTED_MCP_URL = "https://nyx-api.chrono-ai.fun/mcp";

/**
 * Install commands for the published plugins. Both marketplaces are read from
 * the NyxID repository (`.claude-plugin/marketplace.json` and
 * `.agents/plugins/marketplace.json`, generated by scripts/sync-plugins.py).
 * The Claude Code MCP server of plugin `nyxid` is named `plugin:nyxid:nyxid`.
 */
export const PLUGIN_COMMANDS = [
  {
    name: "Claude Code",
    command:
      "claude plugin marketplace add ChronoAIProject/NyxID\nclaude plugin install nyxid@nyxid\nclaude mcp login plugin:nyxid:nyxid",
  },
  {
    name: "Codex",
    command:
      "codex plugin marketplace add ChronoAIProject/NyxID\ncodex plugin add nyxid@nyxid\ncodex mcp login nyxid",
  },
] as const;
